theme: "jekyll-theme-midnight"
title: "The Portfolio of Dylan M Danser"
description: "Welcome to my portfolio! All feedback is welcome and appreciated."

![OfficeRumble](assets/images/OfficeRumble.png)